/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./lib/client"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Category: { // root type
    id: number; // Int!
  }
  Events: { // root type
    date: string; // String!
    id: number; // Int!
    name: string; // String!
    ticketFee: number; // Int!
  }
  Location: { // root type
    id: number; // Int!
    name: string; // String!
  }
  Mutation: {};
  Query: {};
  SubCategory: { // root type
    id: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Category: { // field return type
    id: number; // Int!
  }
  Events: { // field return type
    date: string; // String!
    id: number; // Int!
    location: NexusGenRootTypes['Location']; // Location!
    name: string; // String!
    ticketFee: number; // Int!
  }
  Location: { // field return type
    id: number; // Int!
    name: string; // String!
  }
  Mutation: { // field return type
    addEvent: NexusGenRootTypes['Events']; // Events!
    addLocation: NexusGenRootTypes['Location']; // Location!
  }
  Query: { // field return type
    categories: Array<NexusGenRootTypes['Category'] | null>; // [Category]!
    events: Array<NexusGenRootTypes['Events'] | null>; // [Events]!
    locations: Array<NexusGenRootTypes['Location'] | null>; // [Location]!
    subcategories: Array<NexusGenRootTypes['SubCategory'] | null>; // [SubCategory]!
  }
  SubCategory: { // field return type
    id: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Category: { // field return type name
    id: 'Int'
  }
  Events: { // field return type name
    date: 'String'
    id: 'Int'
    location: 'Location'
    name: 'String'
    ticketFee: 'Int'
  }
  Location: { // field return type name
    id: 'Int'
    name: 'String'
  }
  Mutation: { // field return type name
    addEvent: 'Events'
    addLocation: 'Location'
  }
  Query: { // field return type name
    categories: 'Category'
    events: 'Events'
    locations: 'Location'
    subcategories: 'SubCategory'
  }
  SubCategory: { // field return type name
    id: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addEvent: { // args
      date: string; // String!
      location: string; // String!
      name: string; // String!
      ticketFee: number; // Int!
    }
    addLocation: { // args
      name: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}